// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetConfig():Promise<models.Configuration>;

export function GetHistory(arg1:string):Promise<Array<models.TestResult>>;

export function GetHistoryRange(arg1:string):Promise<Array<models.TestResult>>;

export function GetRegions():Promise<Record<string, models.Region>>;

export function ManualTest(arg1:models.Endpoint):Promise<models.TestResult>;

export function SaveConfig(arg1:models.Configuration):Promise<string>;
