// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddEndpoint(arg1:models.Endpoint):Promise<string>;

export function DeleteEndpoint(arg1:string,arg2:string):Promise<string>;

export function GenerateEndpointID(arg1:string,arg2:models.EndpointType):Promise<string>;

export function GetConfig():Promise<models.Configuration>;

export function GetHistory(arg1:string):Promise<Array<models.TestResult>>;

export function GetHistoryRange(arg1:string):Promise<Array<models.TestResult>>;

export function GetRegions():Promise<Record<string, models.Region>>;

export function HideWindow():Promise<void>;

export function InitSystemTray():Promise<void>;

export function ManualTest(arg1:models.Endpoint):Promise<models.TestResult>;

export function OpenLogDirectory():Promise<void>;

export function QuitApp():Promise<void>;

export function ReorderEndpoints(arg1:string,arg2:Array<string>):Promise<string>;

export function SaveConfig(arg1:models.Configuration):Promise<string>;

export function ShowWindow():Promise<void>;

export function UpdateEndpoint(arg1:string,arg2:string,arg3:models.Endpoint):Promise<string>;

export function WindowResized():Promise<void>;
