// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetHistoryRange(arg1) {
  return window['go']['main']['App']['GetHistoryRange'](arg1);
}

export function GetRegions() {
  return window['go']['main']['App']['GetRegions']();
}

export function ManualTest(arg1) {
  return window['go']['main']['App']['ManualTest'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
