// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {storage} from '../models';

export function GetConfiguration():Promise<config.Config>;

export function GetMonitoringStatus():Promise<main.MonitoringStatus>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function Greet(arg1:string):Promise<string>;

export function IsRunning():Promise<boolean>;

export function RunManualTest(arg1:string):Promise<storage.TestResult>;

export function SetTheme(arg1:string):Promise<void>;

export function Shutdown():Promise<void>;

export function StartMonitoring():Promise<void>;

export function StopMonitoring():Promise<void>;
