// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEndpoint(arg1) {
  return window['go']['main']['App']['AddEndpoint'](arg1);
}

export function GenerateEndpointID(arg1, arg2) {
  return window['go']['main']['App']['GenerateEndpointID'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetHistoryRange(arg1) {
  return window['go']['main']['App']['GetHistoryRange'](arg1);
}

export function GetRegions() {
  return window['go']['main']['App']['GetRegions']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function InitSystemTray() {
  return window['go']['main']['App']['InitSystemTray']();
}

export function ManualTest(arg1) {
  return window['go']['main']['App']['ManualTest'](arg1);
}

export function OpenLogDirectory() {
  return window['go']['main']['App']['OpenLogDirectory']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function WindowResized() {
  return window['go']['main']['App']['WindowResized']();
}
